'''
Problem
A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.

An example of a length 21 DNA string (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."

Given: A DNA string ss of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in ss.

http://rosalind.info/problems/dna/
'''


import re

s="CGACCAGACCGCCTGCGGTTAGCTCTGCGATAACAAAAGCTGTTAAGTTTGCCTATTCAGGCCGTTTTCAAGGGCTGTAAGACCACTCCCTAGCGAGCTAAGTAGCTTGCAGGCTGCGTTTATGGGCCAAGACCGTTGCTACGCCGAAAGCCAATGGTGACCGTACCCATATCACCCGCATCGATAGCCGCCCGAAACATCCGCCTGAACCATGGCAGGTGGTAACTTTCGCTTTCTAGATGATACGATTAGAGATAACACTGAGGGGCAGCTTCCAATCAGCGAAACTTCGTACAGTGGGCCCGTCTAGAAGACCTGAGTTGGCAGACATCCGTCTACGAAATCCGCTGGTTTAATCTAAAAGGCGGAGGTGCATAATCCCTGTATTGATTCGTCGAGAAAAACGCGTTAAGTCTGATCCGTGATCCTGGCGGTGAGGGACCGCTCCACCAAATGTCACTCTGACTTTGTCGGCGCGGTCCGGTGGATGCTTCTCCTGGTCTTAGTGCTGGAGAAGTAACGGCGAAGCTCGCCGGTCCCAGCGGTTTCGGTCACATCAAGCATTCTAAATAGACCTAAAGTTTCCATATCGTAGGAAAAGCGCCGAGTCCCTATAAGGTCACGGACCGGGAACTAAGGGGCCAGGGATAGGCTGTTGCGTAGACAGAAAGAGTTCCACCCTCCTGACATGCATGGGTTCACAACTGCAGACAATGCTCCTATCCTGCCCCACTCGCCACTCACCAGCGTGCAAATAATTGTCAGAATTAGGCCAATTCATGGCTGGGCACCTTACAAGAACCCACCTC"

# str.count(sub, start= 0,end=len(string))
s1="A";
s2="C";
s3="G";
s4="T";

print (s.count(s1,0,len(s))," ",s.count(s2,0,len(s))," ",s.count(s3,0,len(s))," ",s.count(s4,0,len(s)))

